version: "3.4"
services:

  runner:
    image: webrunners/gitlab-runner-service:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - EXECUTOR
      - MAINTAIN
      - OPTIONS
      - SERVICE
      - TAG_LIST
      - TOKEN
      - URL
      - VOLUMES
    deploy:
      replicas: 1
