version: "3."
services:

  runner:
    image: webrunners/gitlab-runner-service:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - COMPOSE_PROJECT_NAME
      - EXECUTOR
      - TOKEN
      - TAG_LIST
      - URL
    deploy:
      replicas: 1
