version: "3.3"
services:

  main:
    image: jwilder/whoami
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 10M
      replicas: 3
