version: "3.3"
services:

  main:
    image: jwilder/whoami
    networks:
      - proxy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 10M
      replicas: 3
      labels:
        com.df.notify: "true"
        com.df.service_port: "8000"
        com.df.domain: "$DOMAIN"
        com.df.no_auth: "${NO_AUTH:-0}"

networks:
  proxy:
    external: true
